### ISSUE TITLE
Ошибки во время билда

### ISSUE THREAD

**Issue by stayfuneral** [alejandro-yakovlev/symfony-docker#1]
Добрый день!

При билде проекта docker-compose выдавал ошибку

`ERROR: The Compose file '././docker/docker-compose.yml' is invalid because:
services.postgres.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object`

Проблема была решена с помощью аргумента --env-file:

`
docker-compose -f ./docker/docker-compose.yml --env-file ./docker/.env build
`

**Comment by MaksimLit** [comment]
> 

Спасибо! Была та же проблема, ваше решение помогло.

**Comment by alejandro-yakovlev** [comment]
Спасибо! Добавил изменения в репозиторий.
