### ISSUE TITLE
ERROR on docker building at php-fpm stage 17/18 in case 

### ISSUE THREAD

**Issue by proKGB1st** [alejandro-yakovlev/symfony-docker#11]
1.116 Composer plugins have been disabled for safety in this non-interactive session. 
Set COMPOSER_ALLOW_SUPERUSER=1 if you want to allow plugins to run as root/super user.

**Comment by q3dm15** [comment]
Сорян. Непредвиденный отвал промежуточных хостов в раше на строне провайдера. Прокси решила проблему!
