### ISSUE TITLE
DDD Violation: AuthUserInterface.php - Using Symfony Security component inside domain

### ISSUE THREAD

**Issue by wassimbkd** [alejandro-yakovlev/symfony-docker#8]
**File Name:** src/Shared/Domain/Security/AuthUserInterface.php

**Violation Description:**

Current implementation in the file violates the principles of Domain-Driven Design by extending UserInterface and PasswordAuthenticated and UserInterface from symfony.

**Comment by alejandro-yakovlev** [comment]
> **File Name:** src/Shared/Domain/Security/AuthUserInterface.php
> 
> **Violation Description:**
> 
> Current implementation in the file violates the principles of Domain-Driven Design by extending UserInterface and PasswordAuthenticated and UserInterface from symfony.

Thanks for the comment. What solution can you suggest to solve this violation?

**Comment by q3dm15** [comment]
![image](https://github.com/alejandro-yakovlev/symfony-docker/assets/133960645/9c715704-d112-46e9-b65b-27f793d4bdc6)
